apiVersion: apps/v1
kind: Deployment
metadata:
  name: colabri-app
  namespace: colabri
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: colabri-app
          image: colabri-app:v0.0.1t
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: colabri-secrets
                  key: db-url
            - name: SECURE_COOKIES
              value: "true"
            - name: CLOUD_AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: colabri-secrets
                  key: cloud-auth-jwt-secret
            - name: CLOUD_SERVICE_DOMAIN
              value: "app.colabri-local.cloud"
            - name: CLOUD_DOC_SERVICE_DOMAIN
              value: "colabri-doc-service"
            - name: CLOUD_SPELL_SERVICE_DOMAIN
              value: "colabri-spell-service"
            - name: CLOUD_ROOT_DOMAIN
              value: "colabri-local.cloud"
            - name: CLOUD_CORS_ORIGINS
              value: "https://*.colabri-local.cloud,https://colabri-local.cloud"
            - name: OAUTH_WEB_APP_CALLBACK_URL
              value: "https://app.colabri-local.cloud/auth/callback"
            - name: GCP_PROJECT_ID
              value: colabri-local
            - name: GCP_SERVICE_ACCOUNT_KEY_PATH
              value: /var/secrets/google/gcp-colabri-app-key.json
          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/google
              readOnly: true
            - name: appconfig
              mountPath: /app/static/appconfig.js
              subPath: appconfig.js
              readOnly: true
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: gcp-credentials
          secret:
            secretName: colabri-secrets
            items:
              - key: gcp-colabri-app-key.json
                path: gcp-colabri-app-key.json
        - name: appconfig
          secret:
            secretName: colabri-secrets
            items:
              - key: appconfig.js
                path: appconfig.js
