apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colabri-ingress
  namespace: colabri
  annotations:
    cert-manager.io/cluster-issuer: null
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls: null
  rules:
    - host: app.colabri-local.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: colabri-app-service
                port:
                  number: 80
