apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secrets.yaml
  - tls-secrets.yaml

patches:
  - path: ai-deployment-patch.yaml
  - path: app-deployment-patch.yaml
  - path: doc-deployment-patch.yaml
  - path: spell-deployment-patch.yaml
  - path: ingress-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: colabri-ingress
      namespace: colabri
  - path: ingress-controller-patch.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx
  - path: coredns-configmap.yaml
    target:
      kind: ConfigMap
      name: coredns
      namespace: kube-system
