apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: colabri

resources:
  - ../../base

patches:
  - path: app-deployment-patch.yaml
  - path: app-service-patch.yaml
  - path: ingress-patch.yaml
  - path: ingress-controller-patch.yaml
    target:
      kind: Service
      name: ingress-nginx-controller
      namespace: ingress-nginx

replicas:
  - name: colabri-app
    count: 1
