apiVersion: v1
kind: Service
metadata:
  name: colabri-doc-service
  namespace: colabri
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"ports": {"9001": "colabri-doc-backend-config"}}'
spec:
  type: ClusterIP
