apiVersion: apps/v1
kind: Deployment
metadata:
  name: colabri-doc
  namespace: colabri
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: colabri-doc
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: colabri-secrets
                  key: db-url
            - name: CLOUD_SERVICE_DOMAIN
              value: "doc.colabri.cloud"
            - name: CLOUD_APP_SERVICE_DOMAIN
              value: "colabri-app-service"
            - name: CLOUD_ROOT_DOMAIN
              value: "colabri.cloud"
            - name: CLOUD_CORS_ORIGINS
              value: "https://*.colabri.cloud,https://colabri.cloud"
            - name: CLOUD_AUTH_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: colabri-secrets
                  key: cloud-auth-jwt-secret
            - name: GCP_PROJECT_ID
              value: colabri-prd
            - name: GCP_SERVICE_ACCOUNT_KEY_PATH
              value: /var/secrets/google/gcp-colabri-app-key.json
          volumeMounts:
            - name: gcp-credentials
              mountPath: /var/secrets/google
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: gcp-credentials
          secret:
            secretName: colabri-secrets
            items:
              - key: gcp-colabri-app-key.json
                path: gcp-colabri-app-key.json
