apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colabri-ingress
  namespace: colabri
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "colabri-ip"
    networking.gke.io/managed-certificates: "colabri-cert"
spec:
  ingressClassName: null
  rules:
    - host: app.colabri.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: colabri-app-service
                port:
                  number: 80
