apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: colabri

resources:
  - ../../base
  - secrets.yaml
  - managed-certificate.yaml

patches:
  - path: app-deployment-patch.yaml
  - path: app-service-patch.yaml
  - path: ingress-patch.yaml
