apiVersion: v1
kind: Service
metadata:
  name: colabri-app-service
  namespace: colabri
  labels:
    app: colabri-app
spec:
  type: ClusterIP
  selector:
    app: colabri-app
    component: backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
