apiVersion: v1
kind: Service
metadata:
  name: colabri-doc-service
  namespace: colabri
  labels:
    app: colabri-doc
spec:
  type: ClusterIP
  selector:
    app: colabri-doc
    component: backend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: websocket
