apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: colabri-ingress
  namespace: colabri
spec:
  ingressClassName: "nginx"
  rules:
    - host: app.colabri.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: colabri-app-service
                port:
                  number: 80
    - host: doc.colabri.cloud
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: colabri-doc-service
                port:
                  number: 80
          - path: /swagger
            pathType: Prefix
            backend:
              service:
                name: colabri-doc-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: colabri-doc-service
                port:
                  number: 9001
