apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress.yaml
  - app-deployment.yaml
  - app-service.yaml
  - doc-deployment.yaml
  - doc-service.yaml
  - spell-deployment.yaml
  - spell-service.yaml
  - coredns-configmap.yaml
