apiVersion: v1
kind: Service
metadata:
  name: colabri-service
  namespace: colabri
  labels:
    app: colabri
spec:
  type: ClusterIP
  selector:
    app: colabri
    component: backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
