apiVersion: v1
kind: Service
metadata:
  name: colabri-spell-service
  namespace: colabri
  labels:
    app: colabri-spell
spec:
  type: ClusterIP
  selector:
    app: colabri-spell
    component: backend
  ports:
    - port: 80
      targetPort: 8010
      protocol: TCP
      name: http
