apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: colabri

resources:
- ../../base

patches:
- path: deployment-patch.yaml
- path: ingress-patch.yaml

replicas:
- name: colabri-app
  count: 3
